apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
labels:
  - pairs:
      app: longhorn-rwx-test
      purpose: testing
resources:
  - pvc.yaml
  - pod.yaml
  - pod-2.yaml
