apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd
resources:
  - ../base/argocd
  - ../base/cert-manager
  - ../base/cloudnative-pg
  - ../base/kube-prometheus-stack
  - ../base/local-path-provisioner
  - ../base/longhorn
  - ../base/reflector
  - ../base/sealed-secrets
  - ../base/traefik
  - ../base/victoria-logs
  - ../base/ziti-controller
  - ../base/ziti-router
  # - cert-manager-issuer.yaml
  # - ziti-router-ingress.yaml
  # - private-ca.yaml
kind: Kustomization
