apiVersion: v1
kind: ConfigMap
metadata:
  name: ftp-config
data:
  ADDED_FLAGS: "-p 30000:30009"
  FTP_USER_GID: "1000"
  FTP_USER_HOME: "/home/ftpusers/reolink"
  FTP_USER_UID: "1000"
  PUBLICHOST: "192.168.1.1"
