apiVersion: kustomize.config.k8s.io/v1beta1
namespace: ftp
resources:
  - namespace.yaml
  - configmap.yaml
  - sealedsecret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
kind: Kustomization
