apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: speedtest-exporter
    files:
      - exporter.py
generatorOptions:
  disableNameSuffixHash: true

