apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd
resources:
  - cert-manager-issuer.yaml
  - ziti-router-ingress.yaml
  - private-ca.yaml
  - github.com/rancher/local-path-provisioner/deploy?ref=v0.0.32
kind: Kustomization
patches:
  - patch: |-
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: local-path-config
        namespace: local-path-storage
      data:
        config.json: |-
          {
                  "nodePathMap":[
                  {
                          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                          "paths":["/var/local-path-provisioner"]
                  },
                  {
                          "node":"kipsang",
                          "paths":["/opt/local-path-provisioner", "/srv/data"]
                  },
                  {
                          "node":"fordyce",
                          "paths":["/opt/local-path-provisioner", "/srv/data"]
                  },
                  {
                          "node":"walmsley",
                          "paths":["/opt/local-path-provisioner", "/srv/data"]
                  },
                  ]
          }
  - patch: |-
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: rancher.io/local-path
      parameters:
        nodePath: /opt/local-path-provisioner
        pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Delete
  - patch: |-
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: sata-local-path
      provisioner: rancher.io/local-path
      parameters:
        nodePath: /srv/data
        pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Retain
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: local-path-storage
        labels:
          pod-security.kubernetes.io/enforce: privileged
