apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - cert-manager-issuer.yaml
  - coredns-ziti-override.yaml
  - home-assistant.yaml
  - private-ca.yaml
  - ziti-dns-forwarder.yaml
  - ziti-router-ingress.yaml
kind: Kustomization
patches:
