apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: openziti-router
  namespace: openziti
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`rtr.compaan.cloud`)
      services:
        - name: openziti-router-edge
          port: 443
  tls:
    passthrough: true
