apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd
resources:
  - ../../base/argocd
  - ../../base/cert-manager
  - ../../base/cloudnative-pg
  - ../../base/nextcloud-db
  - ../../base/nextcloud
  - ../../base/garage
  - ../../base/ftp
  - ../../base/infra
  - ../../base/kube-prometheus-stack
  - ../../base/local-path-provisioner
  - ../../base/kyverno
  - ../../base/longhorn
  - ../../base/longhorn-admission-hooks
  - ../../base/reflector
  - ../../base/sealed-secrets
  - ../../base/speedtest-exporter
  - ../../base/traefik
  - ../../base/trust-manager
  - ../../base/victoria-logs
  - ../../base/ziti-controller
  - ../../base/ziti-edge-tunnel
  - ../../base/ziti-router
kind: Kustomization
